image: node:latest

stages:
  - deploy

deploy_staging:
  stage: deploy
  only:
    refs:
      - dev
  script:
    - ./scripts/gitlab-ci.sh --env.dev
    - cat file.tar.xz | ssh sb@api.sb.im 'cd ~/www/sb.im/sdwc && ls -A | grep -v 'config.json*' | xargs rm -rf && tar -xJf -'

deploy_production:
  stage: deploy
  only:
    refs:
      - master
  script:
    - ./scripts/gitlab-ci.sh
    - cat file.tar.xz | sbcloud@sbnet.xyz 'cd ~/sdwc && ls -A | grep -v 'config.json*' | xargs rm -rf && tar -xJf -'
