language: node_js

node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  - yarn build

deploy:
  #  provider: script
  #  script:
  #    - git clone --branch=gh-pages https://github.com/SB-IM/SDWC.git
  #    - cp -r `cat Deploylist` SDWC/
  #    - cd SDWC
  #    - git add .
  #    - git -c user.name=$GITHUB_NAME -c user.email=$GITHUB_EMAIL commit -am "Auto Deployment"
  #    - git push https://$GITHUB_API_KEY@github.com/SB-IM/SDWC gh-pages

  provider: pages
  local-dir:
    - dist/
    - samples/
    - index.html
    - robots.txt

  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

