language: node_js

node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  - yarn build

before_deploy:
  - ls
  - mv {assets,dist} /tmp/
  - rm -rf {*,.*}
  - wget https://raw.githubusercontent.com/SB-IM/SDWC/gh-pages/config.json
  - cp /tmp/{assets,dist}/* .
  - ls -a


deploy:
  provider: pages
  fqdn: test.newbe.cc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: dev

