language: node_js

node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  - yarn build

after_script:
  #- ls -a |grep -v dist |grep -v index.html | grep -v \\.$ | grep -v .git$ |xargs rm -r
  - git clone --branch=gh-pages https://github.com/SB-IM/SDWC.git
  #- ls
  - cp -r `cat Deploylist` SDWC/
  - cd SDWC
    #- cp -r ../dist ../index.html ./
    #git init
  - git add .
    #- tar -cJf tmp.tar.xz dist index.html
    #- rm -r dist index.html
    #- git checkout gh-pages
    #- git pull
    #- tar -xJf tmp.tar.xz
    #- rm tmp.tar.xz
    #git pull
    #git commit -m "Auto update"
  - git -c user.name=$GITHUB_NAME -c user.email=$GITHUB_EMAIL commit -am "Auto Deployment"
    #git push -f -q https://$GITHUB_NAME:$GITHUB_API_KEY@github.com/SB-IM/SDWC gh-pages
  - git push https://$GITHUB_API_KEY@github.com/SB-IM/SDWC gh-pages

  #- ls dist/
  #- git checkout gh-pages
  #- git commit -m "Auto update"
  #- git push "https://${GH_TOKEN}@${GH_REF}" gh-pages
